import { initializeApp } from 'https://www.gstatic.com/firebasejs/12.2.1/firebase-app.js';
import { getAuth, GoogleAuthProvider, createUserWithEmailAndPassword, signInWithEmailAndPassword, signInWithPopup, sendEmailVerification, updateProfile, onAuthStateChanged, signOut } from 'https://www.gstatic.com/firebasejs/12.2.1/firebase-auth.js';
import { getFirestore, doc, getDoc, setDoc, updateDoc, collection, getDocs, addDoc, query, orderBy, limit, onSnapshot, serverTimestamp, writeBatch } from 'https://www.gstatic.com/firebasejs/12.2.1/firebase-firestore.js';

const firebaseConfig={apiKey:'AIzaSyCxaE30HO0NrEvjRZbp2Qa1V2RCzpVQ8Y4',authDomain:'soro-7f7f3.firebaseapp.com',projectId:'soro-7f7f3',storageBucket:'soro-7f7f3.firebasestorage.app',messagingSenderId:'793394051299',appId:'1:793394051299:web:f259b281218375d3c82dd6'};
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app),google=new GoogleAuthProvider();google.setCustomParameters({prompt:'select_account'});
const dialog=document.querySelector('#auth-dialog'),form=document.querySelector('#auth-form'),message=document.querySelector('#auth-message'),gate=document.querySelector('#gate-screen'),adminPanel=document.querySelector('#admin-panel'),memberList=document.querySelector('#member-list'),adminMessage=document.querySelector('#admin-message'),activityList=document.querySelector('#activity-list'),crewRoom=document.querySelector('#crew-room'),messageList=document.querySelector('#message-list'),messageForm=document.querySelector('#message-form'),messageInput=document.querySelector('#message-input'),roomMessage=document.querySelector('#room-message'),enterCrew=document.querySelector('#enter-crew'),replyBar=document.querySelector('#reply-bar'),replyName=document.querySelector('#reply-name'),replyText=document.querySelector('#reply-text'),pendingAlert=document.querySelector('#pending-alert');
let mode='signin',currentMember=null,unsubscribeMessages=null,replyTarget=null;
function setMessage(text,error=false){message.textContent=text;message.classList.toggle('error',error)}
function authError(err,fallback='Authentication failed.'){const code=err?.code?` [${err.code}]`:'';return `${(err?.message||fallback).replace('Firebase: ','').replace(/\s*\(auth\/[^)]+\)\.?/,'').trim()}${code}`}
function setMode(next){mode=next;document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));document.querySelector('#name-wrap').classList.toggle('hidden',mode!=='signup');document.querySelector('#auth-title').textContent=mode==='signup'?'Create account':'Sign in';document.querySelector('#auth-copy').textContent=mode==='signup'?'Create an account. Crew access begins after administrator approval.':'Approved crew members can enter SỌ̀RỌ̀.';document.querySelector('#email-submit').textContent=mode==='signup'?'Create account':'Sign in';document.querySelector('#password').autocomplete=mode==='signup'?'new-password':'current-password';setMessage('')}
async function ensureMember(user){const ref=doc(db,'members',user.uid),snap=await getDoc(ref);if(!snap.exists()){await setDoc(ref,{uid:user.uid,email:user.email||'',displayName:user.displayName||'',photoURL:user.photoURL||'',role:'member',status:'pending',provider:user.providerData?.[0]?.providerId||'password',createdAt:serverTimestamp(),updatedAt:serverTimestamp()});return {uid:user.uid,email:user.email||'',displayName:user.displayName||'',status:'pending',role:'member'}}return {id:snap.id,...snap.data()}}
function showGate(status){gate.classList.remove('hidden');crewRoom.classList.add('hidden');const title=document.querySelector('#gate-title'),copy=document.querySelector('#gate-copy'),eyebrow=document.querySelector('#gate-eyebrow');enterCrew.classList.toggle('hidden',status!=='approved');if(status==='approved'){eyebrow.textContent='ACCESS APPROVED';title.textContent='Welcome to SỌ̀RỌ̀';copy.textContent='Your crew access is approved. Enter the private crew room.'}else if(status==='rejected'){eyebrow.textContent='ACCESS NOT APPROVED';title.textContent='Membership not approved';copy.textContent='This account does not currently have access to the SỌ̀RỌ̀ crew network.'}else if(status==='suspended'){eyebrow.textContent='ACCESS SUSPENDED';title.textContent='Account suspended';copy.textContent='Your SỌ̀RỌ̀ crew access is currently suspended.'}else{eyebrow.textContent='CREW ACCESS';title.textContent='Account pending approval';copy.textContent='Your account has been created. A SỌ̀RỌ̀ administrator must approve your membership before you can enter the private crew network.'}}
function stopMessages(){if(unsubscribeMessages){unsubscribeMessages();unsubscribeMessages=null}}
function clearReply(){replyTarget=null;replyBar.classList.add('hidden');replyName.textContent='';replyText.textContent=''}
function hideGate(){gate.classList.add('hidden');adminPanel.classList.add('hidden');crewRoom.classList.add('hidden');enterCrew.classList.add('hidden');stopMessages();clearReply();currentMember=null}
function confirmAction(action,member){const name=member.displayName||member.email||'this member';return window.confirm(`${action} ${name}?\n\nThis action will change their SỌ̀RỌ̀ account access or permissions.`)}
function activityPayload(type,member,from,to,email){const data={type,actorUid:auth.currentUser.uid,actorName:currentMember?.displayName||auth.currentUser.displayName||'Crew member',memberUid:member.id||member.uid,memberName:member.displayName||'Unnamed member',from:from||'',to:to||'',createdAt:serverTimestamp()};if(email!==undefined)data.email=email;return data}
async function logSignIn(member){try{await addDoc(collection(db,'activityLog'),activityPayload('sign_in',member,'','successful',auth.currentUser.email||''))}catch(err){console.error('Sign-in activity log failed',err)}}
function memberCard(member){const row=document.createElement('article');row.className='member-card';const identity=document.createElement('div');identity.className='member-identity';const name=document.createElement('strong');name.textContent=member.displayName||'Unnamed member';const email=document.createElement('span');email.textContent=member.email||'No email';const badges=document.createElement('div');badges.className='member-badges';const role=document.createElement('span');role.className='badge';role.textContent=member.role||'member';const status=document.createElement('span');status.className=`badge status-${member.status||'pending'}`;status.textContent=member.status||'pending';badges.append(role,status);identity.append(name,email,badges);row.append(identity);if(member.role!=='owner'){const actions=document.createElement('div');actions.className='member-actions';[['Approve','approved'],['Reject','rejected'],['Suspend','suspended']].forEach(([label,value])=>{const button=document.createElement('button');button.type='button';button.className=value==='approved'?'approve-btn':'secondary small';button.textContent=label;button.disabled=member.status===value;button.addEventListener('click',()=>{if(confirmAction(label,member))changeStatus(member,value)});actions.append(button)});if(currentMember?.role==='owner'&&member.status==='approved'){const roleButton=document.createElement('button');roleButton.type='button';roleButton.className='secondary small role-btn';const promoting=member.role!=='admin';roleButton.textContent=promoting?'Promote to admin':'Demote to member';roleButton.addEventListener('click',()=>{const action=promoting?'Promote to admin':'Demote to member';if(confirmAction(action,member))changeRole(member,promoting?'admin':'member')});actions.append(roleButton)}row.append(actions)}return row}
function updateAdminStats(members){const counts={approved:0,pending:0,suspended:0,rejected:0};members.forEach(member=>{if(Object.hasOwn(counts,member.status))counts[member.status]++});document.querySelector('#stat-total').textContent=members.length;Object.entries(counts).forEach(([status,count])=>document.querySelector(`#stat-${status}`).textContent=count);pendingAlert.textContent=counts.pending?`${counts.pending} awaiting approval`:'';pendingAlert.classList.toggle('hidden',!counts.pending)}
function formatActivityTime(timestamp){if(!timestamp?.toDate)return 'Just now';return timestamp.toDate().toLocaleString([],{day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'})}
function renderActivity(snapshot){activityList.replaceChildren();if(snapshot.empty){const tr=document.createElement('tr'),td=document.createElement('td');td.colSpan=5;td.className='activity-empty';td.textContent='No activity recorded yet.';tr.append(td);activityList.append(tr);return}snapshot.forEach(d=>{const a=d.data(),tr=document.createElement('tr');const values=[formatActivityTime(a.createdAt),a.type==='sign_in'?'Sign in':a.type==='role_change'?'Role change':'Status change',a.type==='sign_in'?`${a.memberName||'Member'}${a.email?` — ${a.email}`:''}`:a.memberName||'Member',a.type==='sign_in'?'—':a.actorName||'Administrator',a.type==='sign_in'?'Successful':`${a.from||'—'} → ${a.to||'—'}`];values.forEach(value=>{const td=document.createElement('td');td.textContent=value;tr.append(td)});activityList.append(tr)})}
async function loadActivity(){if(!currentMember||!['owner','admin'].includes(currentMember.role))return;try{const q=query(collection(db,'activityLog'),orderBy('createdAt','desc'),limit(100));renderActivity(await getDocs(q))}catch(err){console.error(err);activityList.innerHTML='<tr><td colspan="5" class="activity-empty">Could not load activity.</td></tr>'}}
async function loadMembers(){if(!currentMember||!['owner','admin'].includes(currentMember.role))return;adminMessage.textContent='Loading crew…';memberList.replaceChildren();try{const snap=await getDocs(collection(db,'members'));const members=snap.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>{const order={pending:0,approved:1,suspended:2,rejected:3};return (order[a.status]??9)-(order[b.status]??9)});updateAdminStats(members);members.forEach(m=>memberList.append(memberCard(m)));await loadActivity();adminMessage.textContent=`Updated ${new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}.`}catch(err){console.error(err);adminMessage.textContent=`Could not load crew. ${err.code||''}`}}
async function changeStatus(member,status){adminMessage.textContent='Updating member…';try{const batch=writeBatch(db),memberRef=doc(db,'members',member.id||member.uid),activityRef=doc(collection(db,'activityLog'));batch.update(memberRef,{status,updatedAt:serverTimestamp()});batch.set(activityRef,activityPayload('status_change',member,member.status||'',status));await batch.commit();await loadMembers()}catch(err){console.error(err);adminMessage.textContent=`Update failed. ${err.code||''}`}}
async function changeRole(member,role){if(currentMember?.role!=='owner')return;adminMessage.textContent=role==='admin'?'Promoting member…':'Removing admin role…';try{const batch=writeBatch(db),memberRef=doc(db,'members',member.id||member.uid),activityRef=doc(collection(db,'activityLog'));batch.update(memberRef,{role,updatedAt:serverTimestamp()});batch.set(activityRef,activityPayload('role_change',member,member.role||'',role));await batch.commit();await loadMembers()}catch(err){console.error(err);adminMessage.textContent=`Role update failed. ${err.code||''}`}}
async function activateMember(member){currentMember=member;showGate(member.status);const canManage=member.status==='approved'&&['owner','admin'].includes(member.role);adminPanel.classList.toggle('hidden',!canManage);if(canManage)await loadMembers()}
function formatTime(timestamp){if(!timestamp?.toDate)return 'sending…';return timestamp.toDate().toLocaleString([],{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'})}
function selectReply(id,data){replyTarget={id,displayName:data.displayName||'Crew member',text:data.text||''};replyName.textContent=replyTarget.displayName;replyText.textContent=replyTarget.text.length>120?`${replyTarget.text.slice(0,120)}…`:replyTarget.text;replyBar.classList.remove('hidden');messageInput.focus()}
function replyPreview(data){if(!data.replyTo)return null;const preview=document.createElement('button');preview.type='button';preview.className='reply-preview';const name=document.createElement('strong');name.textContent=data.replyTo.displayName||'Crew member';const text=document.createElement('span');text.textContent=data.replyTo.text||'Message';preview.append(name,text);preview.addEventListener('click',()=>{const target=document.querySelector(`[data-message-id="${CSS.escape(data.replyTo.id)}"]`);if(target){target.scrollIntoView({behavior:'smooth',block:'center'});target.classList.add('message-highlight');setTimeout(()=>target.classList.remove('message-highlight'),1200)}});return preview}
function renderMessages(snapshot){messageList.replaceChildren();if(snapshot.empty){const empty=document.createElement('p');empty.className='room-empty';empty.textContent='No messages yet. Start the crew conversation.';messageList.append(empty);return}snapshot.forEach(d=>{const data=d.data(),item=document.createElement('article');item.dataset.messageId=d.id;item.className=`chat-message${data.uid===auth.currentUser?.uid?' own':''}`;const meta=document.createElement('div');meta.className='message-meta';const sender=document.createElement('strong');sender.textContent=data.displayName||'Crew member';const time=document.createElement('time');time.textContent=formatTime(data.createdAt);const body=document.createElement('p');body.textContent=data.text||'';const reply=replyPreview(data);const actions=document.createElement('div');actions.className='message-actions';const replyButton=document.createElement('button');replyButton.type='button';replyButton.textContent='Reply';replyButton.addEventListener('click',()=>selectReply(d.id,data));actions.append(replyButton);meta.append(sender,time);item.append(meta);if(reply)item.append(reply);item.append(body,actions);messageList.append(item)});messageList.scrollTop=messageList.scrollHeight}
function openCrewRoom(){if(!currentMember||currentMember.status!=='approved')return;gate.classList.add('hidden');crewRoom.classList.remove('hidden');roomMessage.textContent='';clearReply();stopMessages();const q=query(collection(db,'messages'),orderBy('createdAt','asc'),limit(200));unsubscribeMessages=onSnapshot(q,renderMessages,err=>{console.error(err);roomMessage.textContent=`Could not load messages. ${err.code||''}`})}
enterCrew.addEventListener('click',openCrewRoom);document.querySelector('#cancel-reply').addEventListener('click',clearReply);document.querySelectorAll('[data-auth-open]').forEach(b=>b.addEventListener('click',()=>dialog.showModal()));document.querySelector('.close').addEventListener('click',()=>dialog.close());document.querySelectorAll('.tab').forEach(b=>b.addEventListener('click',()=>setMode(b.dataset.mode)));document.querySelector('#gate-signout').addEventListener('click',()=>signOut(auth));document.querySelector('#room-signout').addEventListener('click',()=>signOut(auth));document.querySelector('#refresh-members').addEventListener('click',loadMembers);
messageForm.addEventListener('submit',async e=>{e.preventDefault();const text=messageInput.value.trim();if(!text||!currentMember||currentMember.status!=='approved'||!auth.currentUser)return;const button=messageForm.querySelector('button'),payload={text,uid:auth.currentUser.uid,displayName:currentMember.displayName||auth.currentUser.displayName||'Crew member',createdAt:serverTimestamp()};if(replyTarget)payload.replyTo={id:replyTarget.id,displayName:replyTarget.displayName,text:replyTarget.text.slice(0,240)};button.disabled=true;roomMessage.textContent='';try{await addDoc(collection(db,'messages'),payload);messageInput.value='';clearReply();messageInput.focus()}catch(err){console.error(err);roomMessage.textContent=`Message not sent. ${err.code||''}`}finally{button.disabled=false}});
form.addEventListener('submit',async e=>{e.preventDefault();setMessage('Working…');const email=document.querySelector('#email').value.trim(),password=document.querySelector('#password').value,name=document.querySelector('#display-name').value.trim();try{if(mode==='signup'){const cred=await createUserWithEmailAndPassword(auth,email,password);if(name)await updateProfile(cred.user,{displayName:name});await ensureMember(cred.user);await sendEmailVerification(cred.user);dialog.close();showGate('pending')}else{const cred=await signInWithEmailAndPassword(auth,email,password);if(!cred.user.emailVerified){await sendEmailVerification(cred.user);setMessage('Verify your email first. A new verification email has been sent.',true);return}const member=await ensureMember(cred.user);await logSignIn(member);dialog.close();await activateMember(member)}}catch(err){setMessage(authError(err),true)}});
document.querySelector('#google-auth').addEventListener('click',async e=>{e.preventDefault();setMessage('Opening Google account selection…');try{const cred=await signInWithPopup(auth,google);setMessage('Google account connected. Checking crew access…');const member=await ensureMember(cred.user);await logSignIn(member);dialog.close();await activateMember(member)}catch(err){console.error('Google popup sign-in failed',err);if(err?.code==='auth/popup-closed-by-user')setMessage('Google sign-in window was closed before sign-in completed. Please try again.',true);else if(err?.code==='auth/popup-blocked')setMessage('Your browser blocked the Google sign-in window. Allow pop-ups for this site and try again. [auth/popup-blocked]',true);else if(err?.code==='auth/unauthorized-domain')setMessage('This SỌ̀RỌ̀ web address is not authorized in Firebase Authentication. [auth/unauthorized-domain]',true);else setMessage(authError(err,'Google sign-in failed.'),true)}});
onAuthStateChanged(auth,async user=>{if(!user){hideGate();return}try{if(user.providerData.some(p=>p.providerId==='password')&&!user.emailVerified){showGate('pending');document.querySelector('#gate-title').textContent='Verify your email';document.querySelector('#gate-copy').textContent='Check your inbox and verify your email address. After verification, sign in again. Your membership will then remain pending until an administrator approves it.';return}await activateMember(await ensureMember(user))}catch(e){console.error(e)}});
setMode('signin');
