import { initializeApp } from 'https://www.gstatic.com/firebasejs/12.2.1/firebase-app.js';
import { getAuth, GoogleAuthProvider, createUserWithEmailAndPassword, signInWithEmailAndPassword, signInWithPopup, sendEmailVerification, updateProfile, onAuthStateChanged, signOut } from 'https://www.gstatic.com/firebasejs/12.2.1/firebase-auth.js';
import { getFirestore, doc, getDoc, setDoc, updateDoc, collection, getDocs, serverTimestamp } from 'https://www.gstatic.com/firebasejs/12.2.1/firebase-firestore.js';

const firebaseConfig={apiKey:'AIzaSyCxaE30HO0NrEvjRZbp2Qa1V2RCzpVQ8Y4',authDomain:'soro-7f7f3.firebaseapp.com',projectId:'soro-7f7f3',storageBucket:'soro-7f7f3.firebasestorage.app',messagingSenderId:'793394051299',appId:'1:793394051299:web:f259b281218375d3c82dd6'};
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app),google=new GoogleAuthProvider();
google.setCustomParameters({prompt:'select_account'});
const dialog=document.querySelector('#auth-dialog'),form=document.querySelector('#auth-form'),message=document.querySelector('#auth-message'),gate=document.querySelector('#gate-screen'),adminPanel=document.querySelector('#admin-panel'),memberList=document.querySelector('#member-list'),adminMessage=document.querySelector('#admin-message');
let mode='signin',currentMember=null;

function setMessage(text,error=false){message.textContent=text;message.classList.toggle('error',error)}
function authError(err,fallback='Authentication failed.'){const code=err?.code?` [${err.code}]`:'';return `${(err?.message||fallback).replace('Firebase: ','').replace(/\s*\(auth\/[^)]+\)\.?/,'').trim()}${code}`}
function setMode(next){mode=next;document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));document.querySelector('#name-wrap').classList.toggle('hidden',mode!=='signup');document.querySelector('#auth-title').textContent=mode==='signup'?'Create account':'Sign in';document.querySelector('#auth-copy').textContent=mode==='signup'?'Create an account. Crew access begins after administrator approval.':'Approved crew members can enter SỌ̀RỌ̀.';document.querySelector('#email-submit').textContent=mode==='signup'?'Create account':'Sign in';document.querySelector('#password').autocomplete=mode==='signup'?'new-password':'current-password';setMessage('')}
async function ensureMember(user){const ref=doc(db,'members',user.uid),snap=await getDoc(ref);if(!snap.exists()){await setDoc(ref,{uid:user.uid,email:user.email||'',displayName:user.displayName||'',photoURL:user.photoURL||'',role:'member',status:'pending',provider:user.providerData?.[0]?.providerId||'password',createdAt:serverTimestamp(),updatedAt:serverTimestamp()});return {uid:user.uid,status:'pending',role:'member'}}return {id:snap.id,...snap.data()}}
function showGate(status){gate.classList.remove('hidden');const title=document.querySelector('#gate-title'),copy=document.querySelector('#gate-copy'),eyebrow=document.querySelector('#gate-eyebrow');if(status==='approved'){eyebrow.textContent='ACCESS APPROVED';title.textContent='Welcome to SỌ̀RỌ̀';copy.textContent='Your crew access is approved. The private messenger workspace is coming in the next stage.'}else if(status==='rejected'){eyebrow.textContent='ACCESS NOT APPROVED';title.textContent='Membership not approved';copy.textContent='This account does not currently have access to the SỌ̀RỌ̀ crew network.'}else if(status==='suspended'){eyebrow.textContent='ACCESS SUSPENDED';title.textContent='Account suspended';copy.textContent='Your SỌ̀RỌ̀ crew access is currently suspended.'}else{eyebrow.textContent='CREW ACCESS';title.textContent='Account pending approval';copy.textContent='Your account has been created. A SỌ̀RỌ̀ administrator must approve your membership before you can enter the private crew network.'}}
function hideGate(){gate.classList.add('hidden');adminPanel.classList.add('hidden');currentMember=null}
function memberCard(member){const row=document.createElement('article');row.className='member-card';const identity=document.createElement('div');identity.className='member-identity';const name=document.createElement('strong');name.textContent=member.displayName||'Unnamed member';const email=document.createElement('span');email.textContent=member.email||'No email';const badges=document.createElement('div');badges.className='member-badges';const role=document.createElement('span');role.className='badge';role.textContent=member.role||'member';const status=document.createElement('span');status.className=`badge status-${member.status||'pending'}`;status.textContent=member.status||'pending';badges.append(role,status);identity.append(name,email,badges);row.append(identity);
if(member.role!=='owner'){const actions=document.createElement('div');actions.className='member-actions';[['Approve','approved'],['Reject','rejected'],['Suspend','suspended']].forEach(([label,value])=>{const button=document.createElement('button');button.type='button';button.className=value==='approved'?'approve-btn':'secondary small';button.textContent=label;button.disabled=member.status===value;button.addEventListener('click',()=>changeStatus(member.id||member.uid,value));actions.append(button)});row.append(actions)}return row}
async function loadMembers(){if(!currentMember||!['owner','admin'].includes(currentMember.role))return;adminMessage.textContent='Loading crew…';memberList.replaceChildren();try{const snap=await getDocs(collection(db,'members'));const members=snap.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>{const order={pending:0,approved:1,suspended:2,rejected:3};return (order[a.status]??9)-(order[b.status]??9)});members.forEach(m=>memberList.append(memberCard(m)));adminMessage.textContent=`${members.length} crew account${members.length===1?'':'s'}.`}catch(err){console.error(err);adminMessage.textContent=`Could not load crew. ${err.code||''}`}}
async function changeStatus(uid,status){adminMessage.textContent='Updating member…';try{await updateDoc(doc(db,'members',uid),{status,updatedAt:serverTimestamp()});await loadMembers()}catch(err){console.error(err);adminMessage.textContent=`Update failed. ${err.code||''}`}}
async function activateMember(member){currentMember=member;showGate(member.status);const canManage=member.status==='approved'&&['owner','admin'].includes(member.role);adminPanel.classList.toggle('hidden',!canManage);if(canManage)await loadMembers()}

document.querySelectorAll('[data-auth-open]').forEach(b=>b.addEventListener('click',()=>dialog.showModal()));document.querySelector('.close').addEventListener('click',()=>dialog.close());document.querySelectorAll('.tab').forEach(b=>b.addEventListener('click',()=>setMode(b.dataset.mode)));document.querySelector('#gate-signout').addEventListener('click',()=>signOut(auth));document.querySelector('#refresh-members').addEventListener('click',loadMembers);
form.addEventListener('submit',async e=>{e.preventDefault();setMessage('Working…');const email=document.querySelector('#email').value.trim(),password=document.querySelector('#password').value,name=document.querySelector('#display-name').value.trim();try{if(mode==='signup'){const cred=await createUserWithEmailAndPassword(auth,email,password);if(name)await updateProfile(cred.user,{displayName:name});await ensureMember(cred.user);await sendEmailVerification(cred.user);dialog.close();showGate('pending')}else{const cred=await signInWithEmailAndPassword(auth,email,password);if(!cred.user.emailVerified){await sendEmailVerification(cred.user);setMessage('Verify your email first. A new verification email has been sent.',true);return}const member=await ensureMember(cred.user);dialog.close();await activateMember(member)}}catch(err){setMessage(authError(err),true)}});
document.querySelector('#google-auth').addEventListener('click',async e=>{e.preventDefault();setMessage('Opening Google account selection…');try{const cred=await signInWithPopup(auth,google);setMessage('Google account connected. Checking crew access…');const member=await ensureMember(cred.user);dialog.close();await activateMember(member)}catch(err){console.error('Google popup sign-in failed',err);if(err?.code==='auth/popup-closed-by-user')setMessage('Google sign-in window was closed before sign-in completed. Please try again.',true);else if(err?.code==='auth/popup-blocked')setMessage('Your browser blocked the Google sign-in window. Allow pop-ups for this site and try again. [auth/popup-blocked]',true);else if(err?.code==='auth/unauthorized-domain')setMessage('This SỌ̀RỌ̀ web address is not authorized in Firebase Authentication. [auth/unauthorized-domain]',true);else setMessage(authError(err,'Google sign-in failed.'),true)}});
onAuthStateChanged(auth,async user=>{if(!user){hideGate();return}try{if(user.providerData.some(p=>p.providerId==='password')&&!user.emailVerified){showGate('pending');document.querySelector('#gate-title').textContent='Verify your email';document.querySelector('#gate-copy').textContent='Check your inbox and verify your email address. After verification, sign in again. Your membership will then remain pending until an administrator approves it.';return}await activateMember(await ensureMember(user))}catch(e){console.error(e)}});
setMode('signin');
